### ISSUE TITLE
Found MAKE error

### ISSUE THREAD

**Issue by comrade1809** [djhshih/blat#1]
When running the "MAKE" command from ../blat directory after cloning the master branch, there is an error:

`cc -O2  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64   -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc  -o font/mgCourier10.o -c font/mgCourier10.c
font/mgCourier10.c:8:24: fatal error: ../gemfont.h: No such file or directory
 #include "../gemfont.h"
`

The file does exist in **../blat/src/inc**, but the MAKE is searching in **../blat/src** for the file. I had to make a softlink for the file from ../bat/src/inc to ../blat/src for the compilation to finish successfully.

**Comment by djhshih** [comment]
Thanks for the report.

This is a build error inherited upstream. You can see that the gemfont.h clearly does not belong in blat/src/lib (or blat/src)

I've decided that no source change will be made to this poorly implemented blat program, so I never fixed it.
But I've now created a symlink ins blat/src/lib (not blat/src) to work
around this issue.

You should note that the blat results are compiler dependent, non-deterministic, and hence unreliable (See notes on my mlat repo.)

My recommendation for the state-of-the-art full sensitivity aligner is razers3:
https://github.com/seqan/seqan/tree/master/apps/razers3

It outperforms blat in every way.

**Comment by djhshih** [comment]
Fixed in 3b78ec46f47b52d9590dfeface566384c1a795b7

**Comment by comrade1809** [comment]
Thank you for the suggestion, I'm just the implementer of the software. I will let the scientist know about this alternative.
